### ISSUE TITLE
No branch named "v1"; cookiecutter fails

### ISSUE THREAD

**Issue by daefresh** [microsoft/cookiecutter-rust-actix-clean-architecture#1]
cookiecutter -c v1 https://github.com/microsoft/cookiecutter-rust-actix-clean-architecture

doesn't work. 

`-c v1` is the issue, no branch, tag, or commit with `v1`.

**Comment by MDUYN** [comment]
Hey daefresh, I will resolve this

**Comment by MDUYN** [comment]
This has been fixed!
